#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ $# -eq 0 ]; then
    echo "Usage: $0 [--submit | --credentials | --config | --help]"
    exit 1
fi

option=$1

cd "$SCRIPT_DIR" > /dev/null

if [ $option == "--submit" ]; then
    source .env/bin/activate
    python options/Submit.py
    deactivate
elif [ $option == "--status" ]; then
    source .env/bin/activate
    python options/getSubmissionStatusDetails.py
    deactivate
elif [ $option == "--contests" ]; then
    source .env/bin/activate
    python options/getContests.py
    deactivate
elif [ $option == "--my-stats" ]; then
    source .env/bin/activate
    python options/getMyStats.py
    deactivate
elif [ $option == "--my-contests" ]; then
    source .env/bin/activate
    python options/getMyContests.py
    deactivate
elif [ $option == "--credentials" ]; then
    source .env/bin/activate
    python utils/credentials.py
    deactivate
elif [ $option == "--config" ]; then
    source .env/bin/activate
    python config/config_interpreter.py
    deactivate
elif [ $option == "--blogs" ]; then
    source .env/bin/activate
    python options/getBlogs.py
    deactivate
elif [ $option == "--help" ]; then
    cat help.txt
else
    echo "Invalid option. Usage: cftool [--submit | --status | --my-stats | --my-contest | --credentials | --config | --blogs | --help]"
    exit 1
fi

cd - > /dev/null
